travis:
  secure:
    BINSTAR_TOKEN: fiYdMwoBT+h9U1oKSzaz6t1J02LsAxJBjd4lZMhww9kgB4BUsPHvF2dGZzclNHF5d0EYijkkxlMK5Hfon+4C16THQV1pzl7tUgCRCT/wYIVaR5ulR3baxWoyjUYtJFG7nFgZMNCIlPi1rvMdPvZsLTPWTrh5cpMC+bgVPfobIJvFY5cWFvYBTwJ0mVQ1BO/DKzziYBTjaBYr1Wi/E6lv6iGkwiipNKyB7Ke3EyzL/n/Y5US2+5mEE9pPc4dkE4YXPmy4/sa43U/DFW3B3UziA/RCXjXxoCeBQ3+hPwe8A6g9v6OrUImjaz/HJ87q2hjwHfhinnPGpfNlSJMz9fXQ3xLdCBa0EU9NPS1WxL78KrWRRv/feP5wkF1v0NaAby8vRxhBeZSFx1Ff3gl3RGJa2e4OTKO82nia0WJAtoqC0ovA6p/LhYTajl6LOp+pvFqrBcmNLlV4lRJxEmoCM5unF8h++DlLfQEZUbH8BOmAkSyJgLT+mMTl+Zjt6yhcH54tn5UhMlu8r6CX5RzPE7AkKnCvan7UXqL5+o1vKErbctef+Rb1Gr9HPVHf7lTES9D39O6vgZQVLSQRLwl0X/StSNdpkT9eQr7aHqgE7vEqYnV5kS9m63whp7sSgYgbBdgXIYDApGif2JX77Gx44Feh/WmVvD71+EjCJNwIkNd1TKA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
